POST http://localhost:8880/openai/chatCompletion
Content-Type: application/json

{
  "userId": "222222",
  "prompt": "如何学习java"
}

###
POST https://openaiproject-production.up.railway.app/openai/chatCompletion
Content-Type: application/json

{
  "userId": "222222",
  "prompt": "生成一只小鸟的图片"
}

